### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by ef6** [hacdias/webdav#84] opened 2021-08-05 06:18 UTC
```
fatal error: concurrent map writes

goroutine 3482 [running]:
runtime.throw(0x4dc12b, 0x15)
	runtime/panic.go:1116 +0x54 fp=0x4000068940 sp=0x4000068910 pc=0x411d4
runtime.mapassign_faststr(0x45e2e0, 0x400001edb0, 0x40000242a0, 0x12, 0x4000192201)
	runtime/map_faststr.go:211 +0x3c4 fp=0x40000689b0 sp=0x4000068940 pc=0x222d4
github.com/hacdias/webdav/v3/lib.(*Config).ServeHTTP(0x40001a4100, 0x57e3c0, 0x40000c6000, 0x40000fe000)
	github.com/hacdias/webdav/v3/lib/webdav.go:103 +0x388 fp=0x4000068be0 sp=0x40000689b0 pc=0x2d4c48
net/http.serverHandler.ServeHTTP(0x40001de000, 0x57e3c0, 0x40000c6000, 0x40000fe000)
	net/http/server.go:2843 +0xbc fp=0x4000068c10 sp=0x4000068be0 pc=0x279d8c
net/http.(*conn).serve(0x40004041e0, 0x57f800, 0x40001a8040)
	net/http/server.go:1925 +0x6f4 fp=0x4000068fc0 sp=0x4000068c10 pc=0x276074
runtime.goexit()
	runtime/asm_arm64.s:1136 +0x4 fp=0x4000068fc0 sp=0x4000068fc0 pc=0x72874
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x2e8

goroutine 1 [chan receive, 2544 minutes]:
main.main()
	command-line-arguments/main.go:26 +0x114

goroutine 6 [select]:
github.com/hacdias/webdav/v3/lib.LastRequestLogIndex(0x57f800, 0x4000104480)
	github.com/hacdias/webdav/v3/lib/log.go:17 +0x204
created by main.main
	command-line-arguments/main.go:20 +0x70

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7f6220be88, 0x72, 0x0)
	runtime/netpoll.go:222 +0x44
internal/poll.(*pollDesc).wait(0x40001a4198, 0x72, 0x0, 0x0, 0x4d5f54)
	internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0x40001a4180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:394 +0x1a0
net.(*netFD).accept(0x40001a4180, 0x0, 0x4000239b48, 0x27ab8c)
	net/fd_unix.go:172 +0x2c
net.(*TCPListener).accept(0x400019c2a0, 0x6107865e, 0x4000239b78, 0x4baf4)
	net/tcpsock_posix.go:139 +0x2c
net.(*TCPListener).Accept(0x400019c2a0, 0x4000239be0, 0x4000239be8, 0x18, 0x4000001380)
	net/tcpsock.go:261 +0x5c
net/http.(*Server).Serve(0x40001de000, 0x57e140, 0x400019c2a0, 0x0, 0x0)
	net/http/server.go:2937 +0x218
net/http.Serve(...)
	net/http/server.go:2498
github.com/hacdias/webdav/v3/cmd.glob..func1(0x816a60, 0x400019c020, 0x0, 0x2)
	github.com/hacdias/webdav/v3/cmd/root.go:80 +0x33c
github.com/spf13/cobra.(*Command).execute(0x816a60, 0x400001e190, 0x2, 0x2, 0x816a60, 0x400001e190)
	github.com/spf13/cobra@v1.1.3/command.go:856 +0x1c4
github.com/spf13/cobra.(*Command).ExecuteC(0x816a60, 0x0, 0x0, 0x0)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x268
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/hacdias/webdav/v3/cmd.Execute()
	github.com/hacdias/webdav/v3/cmd/cmd.go:9 +0x30
created by main.main
	command-line-arguments/main.go:21 +0x84

goroutine 17 [syscall, 2544 minutes]:
os/signal.signal_recv(0x0)
	runtime/sigqueue.go:147 +0xc4
os/signal.loop()
	os/signal/signal_unix.go:23 +0x20
created by os/signal.Notify.func1.1
	os/signal/signal.go:150 +0x44

goroutine 3483 [IO wait]:
internal/poll.runtime_pollWait(0x7f6220ba00, 0x72, 0x7d04f8)
	runtime/netpoll.go:222 +0x44
internal/poll.(*pollDesc).wait(0x4000400118, 0x72, 0x576f00, 0x7d04f8, 0x0)
	internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x4000400100, 0x40001a61c1, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:159 +0x160
net.(*netFD).Read(0x4000400100, 0x40001a61c1, 0x1, 0x1, 0x40001cef68, 0x270b30, 0x4000104510)
	net/fd_posix.go:55 +0x44
net.(*conn).Read(0x400000e038, 0x40001a61c1, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:182 +0x74
net/http.(*connReader).backgroundRead(0x40001a61b0)
	net/http/server.go:690 +0x50
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:686 +0xc4

goroutine 3523 [IO wait]:
internal/poll.runtime_pollWait(0x7f6220bae8, 0x72, 0x7d04f8)
	runtime/netpoll.go:222 +0x44
internal/poll.(*pollDesc).wait(0x4000400098, 0x72, 0x576f00, 0x7d04f8, 0x0)
	internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x4000400080, 0x4000262041, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:159 +0x160
net.(*netFD).Read(0x4000400080, 0x4000262041, 0x1, 0x1, 0x40001d3768, 0x270b30, 0x40001a8450)
	net/fd_posix.go:55 +0x44
net.(*conn).Read(0x400000e030, 0x4000262041, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:182 +0x74
net/http.(*connReader).backgroundRead(0x4000262030)
	net/http/server.go:690 +0x50
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:686 +0xc4

goroutine 3481 [runnable]:
net/http.Header.Clone(0x40002620f0, 0x7e8100)
	net/http/header.go:102 +0x128
net/http.(*response).WriteHeader(0x40001de0e0, 0x195)
	net/http/server.go:1149 +0x1d4
golang.org/x/net/webdav.(*Handler).ServeHTTP(0x40001a8300, 0x57e3c0, 0x40001de0e0, 0x400019e200)
	golang.org/x/net@v0.0.0-20210614182718-04defd469f4e/webdav/webdav.go:74 +0x104
github.com/hacdias/webdav/v3/lib.(*Config).ServeHTTP(0x40001a4100, 0x57e3c0, 0x40001de0e0, 0x400019e200)
	github.com/hacdias/webdav/v3/lib/webdav.go:159 +0x5f8
net/http.serverHandler.ServeHTTP(0x40001de000, 0x57e3c0, 0x40001de0e0, 0x400019e200)
	net/http/server.go:2843 +0xbc
net/http.(*conn).serve(0x40004040a0, 0x57f800, 0x4000104000)
	net/http/server.go:1925 +0x6f4
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x2e8

goroutine 3510 [IO wait]:
internal/poll.runtime_pollWait(0x7f6220bcb8, 0x72, 0x7d04f8)
	runtime/netpoll.go:222 +0x44
internal/poll.(*pollDesc).wait(0x4000400018, 0x72, 0x576f00, 0x7d04f8, 0x0)
	internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x4000400000, 0x400001e881, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:159 +0x160
net.(*netFD).Read(0x4000400000, 0x400001e881, 0x1, 0x1, 0x40001d3f68, 0x270b30, 0x400031e110)
	net/fd_posix.go:55 +0x44
net.(*conn).Read(0x400000e028, 0x400001e881, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:182 +0x74
net/http.(*connReader).backgroundRead(0x400001e870)
	net/http/server.go:690 +0x50
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:686 +0xc4

goroutine 3461 [IO wait, 266 minutes]:
internal/poll.runtime_pollWait(0x7f6220bbd0, 0x72, 0x7d04f8)
	runtime/netpoll.go:222 +0x44
internal/poll.(*pollDesc).wait(0x4000400298, 0x72, 0x576f00, 0x7d04f8, 0x0)
	internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x4000400280, 0x4000318000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:159 +0x160
net.(*netFD).Read(0x4000400280, 0x4000318000, 0x1000, 0x1000, 0x40000b1768, 0x270e68, 0x0)
	net/fd_posix.go:55 +0x44
net.(*conn).Read(0x400018c048, 0x4000318000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	net/net.go:182 +0x74
net/http.(*connReader).Read(0x40002636e0, 0x4000318000, 0x1000, 0x1000, 0x40000b1848, 0x4b5b0, 0x40000b18e8)
	net/http/server.go:798 +0x244
bufio.(*Reader).fill(0x40002ebec0)
	bufio/bufio.go:101 +0xf8
bufio.(*Reader).ReadSlice(0x40002ebec0, 0x1c60a, 0x400019ea00, 0x100, 0xf8, 0x4c6040, 0x40000b18d8)
	bufio/bufio.go:360 +0x38
bufio.(*Reader).ReadLine(0x40002ebec0, 0x400019ea00, 0x81f580, 0x4000080000, 0x0, 0x81fb00, 0x400000e901)
	bufio/bufio.go:389 +0x30
net/textproto.(*Reader).readLineSlice(0x40004020c0, 0x400019ea00, 0x4000400280, 0xd7500, 0x40000b19c8, 0x6d9ec)
	net/textproto/reader.go:58 +0x60
net/textproto.(*Reader).ReadLine(...)
	net/textproto/reader.go:39
net/http.readRequest(0x40002ebec0, 0x0, 0x400019ea00, 0x0, 0x0)
	net/http/request.go:1012 +0x74
net/http.(*conn).readRequest(0x4000404140, 0x57f800, 0x400031e080, 0x0, 0x0, 0x0)
	net/http/server.go:984 +0x150
net/http.(*conn).serve(0x4000404140, 0x57f800, 0x400031e080)
	net/http/server.go:1851 +0x5ac
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x2e8

goroutine 3480 [runnable]:
net/http.Header.Clone(0x400001f1d0, 0x7e8100)
	net/http/header.go:104 +0x1d0
net/http.(*response).WriteHeader(0x40001500e0, 0x195)
	net/http/server.go:1149 +0x1d4
golang.org/x/net/webdav.(*Handler).ServeHTTP(0x40001a8300, 0x57e3c0, 0x40001500e0, 0x4000020400)
	golang.org/x/net@v0.0.0-20210614182718-04defd469f4e/webdav/webdav.go:74 +0x104
github.com/hacdias/webdav/v3/lib.(*Config).ServeHTTP(0x40001a4100, 0x57e3c0, 0x40001500e0, 0x4000020400)
	github.com/hacdias/webdav/v3/lib/webdav.go:159 +0x5f8
net/http.serverHandler.ServeHTTP(0x40001de000, 0x57e3c0, 0x40001500e0, 0x4000020400)
	net/http/server.go:2843 +0xbc
net/http.(*conn).serve(0x4000404000, 0x57f800, 0x400031e000)
	net/http/server.go:1925 +0x6f4
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x2e8
```

**Comment by Mohammed90** [comment] 2021-08-05 06:39
Duplicate of #82, albeit the other one is reported in Mandarin, I guess.

**Closed by Mohammed90** 2021-08-05 06:39 UTC
